spring.application.name=fitness-service


server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/fitness_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

gemini.api.key=AQ.Ab8RN6IU6w38nHzK17ZVOtr1QR3AdGp0itMXZDkEx2cYfju6Og

# JWT (must be same as User Service)
jwt.secret=MySuperSecretKeyForUserServiceJWTAuthentication123456789
jwt.expiration=3600000
# Swagger
springdoc.swagger-ui.path=/swagger-ui.html